### PR TITLE
Fix intermediate cert loading to registry issue when OCSP validation is disabled

### LINKED ISSUE #12376: Loading Intermediate Cert into registry
**Describe the issue:**
Unable to load Intermediate Cert into registry when the cert only contains CRL endpoint

**How to reproduce:**

- load a particular Intermediate CA into the registry (_/system/governance/repository/security/certificate/certificate-authority) 

- using only CRL validation and have OCSP validation disabled

- pass an empty ocspUrlList

**Expected behavior:**
certificate should be loaded into the registry

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0

---
Dev notes:
`if (ocspUrlList.isEmpty())` is causing the issue:
https://github.com/wso2-support/identity-x509-commons/blob/support-1.0.8/components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java#L783

### PR DESCRIPTION
**Pull request by GANGANI**
## Purpose
Resolves: wso2/product-is#12376

### CODE REVIEW

File: components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java [hunk 1]
```diff
@@ -457,13 +465,25 @@ private static CACertificate resourceToCACertObject(Resource resource) throws Ce
...
+        List<String> crlUrls = new ArrayList<>();
         try {
             if (!registry.resourceExists(caCertRegPath)) {
+                List<Validator> defaultValidatorConfig = getDefaultValidatorConfig(validatorChildElement);
+                for (Validator validator : defaultValidatorConfig) {
+                    if (validator.isEnabled()) {
+                        if (X509CertificateValidationConstants.OCSP_VALIDATOR.equals(validator.getDisplayName())) {
+                            ocspUrls = getAIALocations(certificate);
+                        }
+                        if (X509CertificateValidationConstants.CRL_VALIDATOR.equals(validator.getDisplayName())) {
```
Comment (DinikaSen) [inline components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: Since we check the value of 'validator.getDisplayName()' in both these if statements, can't we use 'else if' for the latter if check?

Comment (GANGANI) [reply components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: Fixed https://github.com/wso2-extensions/identity-x509-commons/pull/20/commits/aa080123a718d304178d0ec2b6e299a54d7eef29

**Review by DinikaSen — APPROVED** [review]

**Review by vihanga-liyanage — APPROVED** [review]
