### PR TITLE
Verify access method before adding OCSP URLs to the list

### LINKED ISSUE #11303: Certificate Validation component does not verify access method during OCSP validation
In the x509 certificate validation jar  the validation logic does not check the access method in the Authority Info Access section before adding accessLocation to the ocspUrlList. As a consequence to this, when we enable OCSP-based certificate validation we are seeing validation requests going out to the wrong endpoint first.

**How to reproduce:**
Configuring X509Certificate Authenticator while disabling CRL-based certificate validation, enabling OCSP-based certificate validation and by adding two entries in "Authority Info Access" section in client's x509 certificate

**Expected behavior:**
Checking  id-ad-ocsp OID appears as accessMethod before adding it in to ocspUrlList.

### PR DESCRIPTION
**Pull request by kalanika**
Fix https://github.com/wso2/product-is/issues/11303

### CODE REVIEW

**Review by sachiniWettasinghe — APPROVED** [review]

File: components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java [hunk 1]
```diff
@@ -885,7 +886,8 @@ public static RevocationStatus getRevocationStatus(X509Certificate peerCert, X50
             for (AccessDescription accessDescription : accessDescriptions) {
 
                 GeneralName gn = accessDescription.getAccessLocation();
-                if (gn.getTagNo() == GeneralName.uniformResourceIdentifier) {
+                if (gn.getTagNo() == GeneralName.uniformResourceIdentifier &&
+                        accessDescription.getAccessMethod().equals(X509ObjectIdentifiers.ocspAccessMethod)) {
```
Comment (somindatommy) [inline components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: is `X509ObjectIdentifiers.ocspAccessMethod` a constant? If that's a const, can we change the order?

Comment (DinikaSen) [reply components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: Addressed in https://github.com/wso2-extensions/identity-x509-commons/pull/13/commits/378a1efb68e4dabc81182abef36294921ec9fd32

File: components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java [hunk 2]
```diff
@@ -884,13 +884,13 @@ public static RevocationStatus getRevocationStatus(X509Certificate peerCert, X50
...
-
-                GeneralName gn = accessDescription.getAccessLocation();
-                if (gn.getTagNo() == GeneralName.uniformResourceIdentifier &&
-                        accessDescription.getAccessMethod().equals(X509ObjectIdentifiers.ocspAccessMethod)) {
-                    DERIA5String str = DERIA5String.getInstance(gn.getName());
-                    String accessLocation = str.getString();
-                    ocspUrlList.add(accessLocation);
+                if (X509ObjectIdentifiers.ocspAccessMethod.equals(accessDescription.getAccessMethod())) {
+                    GeneralName gn = accessDescription.getAccessLocation();
+                    if (gn.getTagNo() == GeneralName.uniformResourceIdentifier) {
```
Comment (somindatommy) [inline components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: can `gn` be null?
can we use equals for `gn.getTagNo() == GeneralName.uniformResourceIdentifier`?

Comment (DinikaSen) [reply components/validation/src/main/java/org/wso2/carbon/identity/x509Certificate/validation/CertificateValidationUtil.java]: Null check added in https://github.com/wso2-extensions/identity-x509-commons/pull/13/commits/335d3408181f632f5012157f26f80c39759b4ecf. Since this comparison is between two 'int' primitives, equals cannot be used.

**Review by somindatommy — APPROVED** [review]
